Collections:
  - Name: VGG
    Metadata:
      Training Data: ImageNet
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x Xp GPUs
      Epochs: 100
      Batch Size: 256
      Architecture:
        - VGG
    Paper: https://arxiv.org/abs/1409.1556
    README: configs/vgg/README.md

Models:
- Config: configs/vgg/vgg11_b32x8_imagenet.py
  In Collection: VGG
  Metadata:
    FLOPs: 7.63 G
    Parameters: 132.86 M
  Name: vgg11_b32x8_imagenet
  Results:
  - Dataset: ImageNet
    Metrics:
      Top 1 Accuracy: 68.75
      Top 5 Accuracy: 88.87
    Task: Image Classification
  Weights: https://download.openmmlab.com/mmclassification/v0/vgg/vgg11_batch256_imagenet_20210208-4271cd6c.pth
- Config: configs/vgg/vgg13_b32x8_imagenet.py
  In Collection: VGG
  Metadata:
    FLOPs: 11.34 G
    Parameters: 133.05 M
  Name: vgg13_b32x8_imagenet
  Results:
  - Dataset: ImageNet
    Metrics:
      Top 1 Accuracy: 70.02
      Top 5 Accuracy: 89.46
    Task: Image Classification
  Weights: https://download.openmmlab.com/mmclassification/v0/vgg/vgg13_batch256_imagenet_20210208-4d1d6080.pth
- Config: configs/vgg/vgg16_b32x8_imagenet.py
  In Collection: VGG
  Metadata:
    FLOPs: 15.5 G
    Parameters: 138.36 M
  Name: vgg16_b32x8_imagenet
  Results:
  - Dataset: ImageNet
    Metrics:
      Top 1 Accuracy: 71.62
      Top 5 Accuracy: 90.49
    Task: Image Classification
  Weights: https://download.openmmlab.com/mmclassification/v0/vgg/vgg16_batch256_imagenet_20210208-db26f1a5.pth
- Config: configs/vgg/vgg19_b32x8_imagenet.py
  In Collection: VGG
  Metadata:
    FLOPs: 19.67 G
    Parameters: 143.67 M
  Name: vgg19_b32x8_imagenet
  Results:
  - Dataset: ImageNet
    Metrics:
      Top 1 Accuracy: 72.41
      Top 5 Accuracy: 90.8
    Task: Image Classification
  Weights: https://download.openmmlab.com/mmclassification/v0/vgg/vgg19_bn_batch256_imagenet_20210208-da620c4f.pth
- Config: configs/vgg/vgg11bn_b32x8_imagenet.py
  In Collection: VGG
  Metadata:
    FLOPs: 7.64 G
    Parameters: 132.87 M
  Name: vgg11bn_b32x8_imagenet
  Results:
  - Dataset: ImageNet
    Metrics:
      Top 1 Accuracy: 70.75
      Top 5 Accuracy: 90.12
    Task: Image Classification
  Weights: https://download.openmmlab.com/mmclassification/v0/vgg/vgg11_bn_batch256_imagenet_20210207-f244902c.pth
- Config: configs/vgg/vgg13bn_b32x8_imagenet.py
  In Collection: VGG
  Metadata:
    FLOPs: 11.36 G
    Parameters: 133.05 M
  Name: vgg13bn_b32x8_imagenet
  Results:
  - Dataset: ImageNet
    Metrics:
      Top 1 Accuracy: 72.15
      Top 5 Accuracy: 90.71
    Task: Image Classification
  Weights: https://download.openmmlab.com/mmclassification/v0/vgg/vgg13_bn_batch256_imagenet_20210207-1a8b7864.pth
- Config: configs/vgg/vgg16_b32x8_imagenet.py
  In Collection: VGG
  Metadata:
    FLOPs: 15.53 G
    Parameters: 138.37 M
  Name: vgg16_b32x8_imagenet
  Results:
  - Dataset: ImageNet
    Metrics:
      Top 1 Accuracy: 73.72
      Top 5 Accuracy: 91.68
    Task: Image Classification
  Weights: https://download.openmmlab.com/mmclassification/v0/vgg/vgg16_bn_batch256_imagenet_20210208-7e55cd29.pth
- Config: configs/vgg/vgg19bn_b32x8_imagenet.py
  In Collection: VGG
  Metadata:
    FLOPs: 19.7 G
    Parameters: 143.68 M
  Name: vgg19bn_b32x8_imagenet
  Results:
  - Dataset: ImageNet
    Metrics:
      Top 1 Accuracy: 74.7
      Top 5 Accuracy: 92.24
    Task: Image Classification
  Weights: https://download.openmmlab.com/mmclassification/v0/vgg/vgg19_bn_batch256_imagenet_20210208-da620c4f.pth
