Collections:
  - Name: VGG
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x Xp GPUs
      Epochs: 100
      Batch Size: 256
      Architecture:
        - VGG
    Paper:
      URL: https://arxiv.org/abs/1409.1556
      Title: "Very Deep Convolutional Networks for Large-Scale Image"
    README: configs/vgg/README.md
    Code:
      URL: https://github.com/open-mmlab/mmclassification/blob/v0.15.0/mmcls/models/backbones/vgg.py#L39
      Version: v0.15.0

Models:
  - Name: vgg11_8xb32_in1k
    Metadata:
      FLOPs: 7630000000
      Parameters: 132860000
    In Collection: VGG
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 68.75
          Top 5 Accuracy: 88.87
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/vgg/vgg11_batch256_imagenet_20210208-4271cd6c.pth
    Config: configs/vgg/vgg11_8xb32_in1k.py
  - Name: vgg13_8xb32_in1k
    Metadata:
      FLOPs: 11340000000
      Parameters: 133050000
    In Collection: VGG
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 70.02
          Top 5 Accuracy: 89.46
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/vgg/vgg13_batch256_imagenet_20210208-4d1d6080.pth
    Config: configs/vgg/vgg13_8xb32_in1k.py
  - Name: vgg16_8xb32_in1k
    Metadata:
      FLOPs: 15500000000
      Parameters: 138360000
    In Collection: VGG
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 71.62
          Top 5 Accuracy: 90.49
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/vgg/vgg16_batch256_imagenet_20210208-db26f1a5.pth
    Config: configs/vgg/vgg16_8xb32_in1k.py
  - Name: vgg19_8xb32_in1k
    Metadata:
      FLOPs: 19670000000
      Parameters: 143670000
    In Collection: VGG
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 72.41
          Top 5 Accuracy: 90.8
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/vgg/vgg19_batch256_imagenet_20210208-e6920e4a.pth
    Config: configs/vgg/vgg19_8xb32_in1k.py
  - Name: vgg11bn_8xb32_in1k
    Metadata:
      FLOPs: 7640000000
      Parameters: 132870000
    In Collection: VGG
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 70.67
          Top 5 Accuracy: 90.16
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/vgg/vgg11_bn_batch256_imagenet_20210207-f244902c.pth
    Config: configs/vgg/vgg11bn_8xb32_in1k.py
  - Name: vgg13bn_8xb32_in1k
    Metadata:
      FLOPs: 11360000000
      Parameters: 133050000
    In Collection: VGG
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 72.12
          Top 5 Accuracy: 90.66
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/vgg/vgg13_bn_batch256_imagenet_20210207-1a8b7864.pth
    Config: configs/vgg/vgg13bn_8xb32_in1k.py
  - Name: vgg16bn_8xb32_in1k
    Metadata:
      FLOPs: 15530000000
      Parameters: 138370000
    In Collection: VGG
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 73.74
          Top 5 Accuracy: 91.66
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/vgg/vgg16_bn_batch256_imagenet_20210208-7e55cd29.pth
    Config: configs/vgg/vgg16bn_8xb32_in1k.py
  - Name: vgg19bn_8xb32_in1k
    Metadata:
      FLOPs: 19700000000
      Parameters: 143680000
    In Collection: VGG
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 74.68
          Top 5 Accuracy: 92.27
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/vgg/vgg19_bn_batch256_imagenet_20210208-da620c4f.pth
    Config: configs/vgg/vgg19bn_8xb32_in1k.py
