Collections:
  - Name: LeViT
    Metadata:
      Training Data: ImageNet-1k
      Architecture:
        - 1x1 Convolution
        - LeViT Attention Block
    Paper:
      Title: "LeViT: a Vision Transformer in ConvNet\u2019s Clothing for Faster Inference"
      URL: https://arxiv.org/abs/2104.01136
    README: configs/levit/README.md
    Code:
      URL: https://github.com/open-mmlab/mmpretrain/blob/main/mmpretrain/models/backbones/levit.py
      Version: v1.0.0rc5

Models:
  - Name: levit-128s_3rdparty_in1k
    Metadata:
      FLOPs: 310342496
      Parameters: 7391290
      Training Data: ImageNet-1k
    In Collection: LeViT
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 76.51
          Top 5 Accuracy: 92.90
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/levit/levit-128s_3rdparty_in1k_20230117-e9fbd209.pth
    Config: configs/levit/levit-128s_8xb256_in1k.py
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/LeViT/LeViT-128S-96703c44.pth
      Code: https://github.com/facebookresearch/LeViT
  - Name: levit-128_3rdparty_in1k
    Metadata:
      FLOPs: 413060992
      Parameters: 8828168
      Training Data: ImageNet-1k
    In Collection: LeViT
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 78.58
          Top 5 Accuracy: 93.95
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/levit/levit-128_3rdparty_in1k_20230117-3be02a02.pth
    Config: configs/levit/levit-128_8xb256_in1k.py
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/LeViT/LeViT-128-b88c2750.pth
      Code: https://github.com/facebookresearch/LeViT
  - Name: levit-192_3rdparty_in1k
    Metadata:
      FLOPs: 667860704
      Parameters: 10561301
      Training Data: ImageNet-1k
    In Collection: LeViT
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 79.86
          Top 5 Accuracy: 94.75
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/levit/levit-192_3rdparty_in1k_20230117-8217a0f9.pth
    Config: configs/levit/levit-192_8xb256_in1k.py
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/LeViT/LeViT-192-92712e41.pth
      Code: https://github.com/facebookresearch/LeViT
  - Name: levit-256_3rdparty_in1k
    Metadata:
      FLOPs: 1141625216
      Parameters: 18379852
      Training Data: ImageNet-1k
    In Collection: LeViT
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 81.59
          Top 5 Accuracy: 95.46
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/levit/levit-256_3rdparty_in1k_20230117-5ae2ce7d.pth
    Config: configs/levit/levit-256_8xb256_in1k.py
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/LeViT/LeViT-256-13b5763e.pth
      Code: https://github.com/facebookresearch/LeViT
  - Name: levit-384_3rdparty_in1k
    Metadata:
      FLOPs: 2372941568
      Parameters: 38358300
      Training Data: ImageNet-1k
    In Collection: LeViT
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 82.59
          Top 5 Accuracy: 95.95
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/levit/levit-384_3rdparty_in1k_20230117-f3539cce.pth
    Config: configs/levit/levit-384_8xb256_in1k.py
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/LeViT/LeViT-384-9bdaf2e2.pth
      Code: https://github.com/facebookresearch/LeViT
