Collections:
  - Name: RevViT
    Metadata:
      Training Data: ImageNet-1k
      Architecture:
        - Vision Transformer
        - Reversible
    Paper:
      URL: https://openaccess.thecvf.com/content/CVPR2022/papers/Mangalam_Reversible_Vision_Transformers_CVPR_2022_paper.pdf
      Title: Reversible Vision Transformers
    README: configs/revvit/README.md
    Code:
      Version: v0.23.4
      URL: https://github.com/open-mmlab/mmclassification/blob/v0.23.4/mmcls/models/backbones/revvit.py

Models:
  - Name: revvitt-small_3rdparty_8xb256_in1k
    Metadata:
      FLOPs: 4457472768
      Parameters: 28589128
    In Collection: RevViT
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 82.05
          Top 5 Accuracy: 95.86
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/convnext/convnext-tiny_3rdparty_32xb128_in1k_20220124-18abde00.pth
    Config: configs/revvit/revvit-small_8xb256_in1k.py
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/convnext/convnext_tiny_1k_224_ema.pth
      Code: https://github.com/facebookresearch/ConvNeXt
  - Name: revvitt-base_3rdparty_8xb256_in1k
    Metadata:
      FLOPs: 4457472768
      Parameters: 28589128
    In Collection: RevViT
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 82.05
          Top 5 Accuracy: 95.86
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/convnext/convnext-tiny_3rdparty_32xb128_in1k_20220124-18abde00.pth
    Config: configs/revvit/revvit-base_8xb256_in1k.py
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/convnext/convnext_tiny_1k_224_ema.pth
      Code: https://github.com/facebookresearch/ConvNeXt
