Collections:
  - Name: SEResNet
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Epochs: 140
      Batch Size: 256
      Architecture:
        - ResNet
    Paper:
      URL: https://openaccess.thecvf.com/content_cvpr_2018/html/Hu_Squeeze-and-Excitation_Networks_CVPR_2018_paper.html
      Title: "Squeeze-and-Excitation Networks"
    README: configs/seresnet/README.md
    Code:
      URL: https://github.com/open-mmlab/mmclassification/blob/v0.15.0/mmcls/models/backbones/seresnet.py#L58
      Version: v0.15.0

Models:
  - Name: seresnet50_8xb32_in1k
    Metadata:
      FLOPs: 4130000000
      Parameters: 28090000
    In Collection: SEResNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 77.74
          Top 5 Accuracy: 93.84
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/se-resnet/se-resnet50_batch256_imagenet_20200804-ae206104.pth
    Config: configs/seresnet/seresnet50_8xb32_in1k.py
  - Name: seresnet101_8xb32_in1k
    Metadata:
      FLOPs: 7860000000
      Parameters: 49330000
    In Collection: SEResNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 78.26
          Top 5 Accuracy: 94.07
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/se-resnet/se-resnet101_batch256_imagenet_20200804-ba5b51d4.pth
    Config: configs/seresnet/seresnet101_8xb32_in1k.py
