Collections:
  - Name: RepLKNet
    Metadata:
      Training Data: ImageNet-1k
      Architecture:
        - Large-Kernel Convolution
        - VGG-style Neural Network
    Paper:
      URL: https://arxiv.org/abs/2203.06717
      Title: 'Scaling Up Your Kernels to 31x31: Revisiting Large Kernel Design in CNNs'
    README: configs/replknet/README.md
    Code:
      URL: https://github.com/open-mmlab/mmclassification/blob/v1.0.0rc3/mmcls/models/backbones/replknet.py
      Version: v1.0.0rc3

Models:
  - Name: replknet-31B_3rdparty_32xb64-coslr-300e_224_in1k
    In Collection: RepLKNet
    Config: configs/replknet/replknet-31B_32xb64-coslr-300e_224_in1k.py
    Metadata:
      FLOPs: 15300000000
      Parameters: 79000000
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 83.48
        Top 5 Accuracy: 96.57
    Weights: https://download.openmmlab.com/mmclassification/v0/repvgg/repvgg-A0_3rdparty_4xb64-coslr-120e_in1k_20210909-883ab98c.pth
    Converted From:
      Weights: https://drive.google.com/u/0/uc?id=1azQUiCxK9feYVkkrPqwVPBtNsTzDrX7S&export=download
      Code: https://github.com/DingXiaoH/RepLKNet-pytorch/blob/main/replknet.py

  - Name: replknet-31B_3rdparty_32xb64-coslr-300e_384_in1k
    In Collection: RepLKNet
    Config: configs/replknet/replknet-31B_32xb64-coslr-300e_384_in1k.py
    Metadata:
      FLOPs: 45100000000
      Parameters: 79000000
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 84.84
        Top 5 Accuracy: 97.34
    Weights: https://download.openmmlab.com/mmclassification/v0/repvgg/repvgg-A0_3rdparty_4xb64-coslr-120e_in1k_20210909-883ab98c.pth
    Converted From:
      Weights: https://drive.google.com/u/0/uc?id=1vo-P3XB6mRLUeDzmgv90dOu73uCeLfZN&export=download
      Code: https://github.com/DingXiaoH/RepLKNet-pytorch/blob/main/replknet.py

  - Name: replknet-31B_3rdparty_32xb64-coslr-300e_224_in22kto1k
    In Collection: RepLKNet
    Config: configs/replknet/replknet-31B_32xb64-coslr-300e_224_in22kto1k.py
    Metadata:
      FLOPs: 15300000000
      Parameters: 79000000
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 85.20
        Top 5 Accuracy: 97.56
    Weights: https://download.openmmlab.com/mmclassification/v0/repvgg/repvgg-A0_3rdparty_4xb64-coslr-120e_in1k_20210909-883ab98c.pth
    Converted From:
      Weights: https://drive.google.com/u/0/uc?id=1DslZ2voXZQR1QoFY9KnbsHAeF84hzS0s&export=download
      Code: https://github.com/DingXiaoH/RepLKNet-pytorch/blob/main/replknet.py

  - Name: replknet-31B_3rdparty_32xb64-coslr-300e_384_in22kto1k
    In Collection: RepLKNet
    Config: configs/replknet/replknet-31B_32xb64-coslr-300e_384_in22kto1k.py
    Metadata:
      FLOPs: 45100000000
      Parameters: 79000000
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 85.99
        Top 5 Accuracy: 97.75
    Weights: https://download.openmmlab.com/mmclassification/v0/repvgg/repvgg-A0_3rdparty_4xb64-coslr-120e_in1k_20210909-883ab98c.pth
    Converted From:
      Weights: https://drive.google.com/u/0/uc?id=1Sc46BWdXXm2fVP-K_hKKU_W8vAB-0duX&export=download
      Code: https://github.com/DingXiaoH/RepLKNet-pytorch/blob/main/replknet.py

  - Name: replknet-31L_3rdparty_32xb64-coslr-300e_384_in22kto1k
    In Collection: RepLKNet
    Config: configs/replknet/replknet-31L_32xb64-coslr-300e_384_in22kto1k.py
    Metadata:
      FLOPs: 96000000000
      Parameters: 172000000
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 86.63
        Top 5 Accuracy: 98.00
    Weights: https://download.openmmlab.com/mmclassification/v0/repvgg/repvgg-A0_3rdparty_4xb64-coslr-120e_in1k_20210909-883ab98c.pth
    Converted From:
      Weights: https://drive.google.com/u/0/uc?id=1JYXoNHuRvC33QV1pmpzMTKEni1hpWfBl&export=download
      Code: https://github.com/DingXiaoH/RepLKNet-pytorch/blob/main/replknet.py

  - Name: replknet-XL_3rdparty_32xb64-coslr-300e_320_meg73mto1k
    In Collection: RepLKNet
    Config: configs/replknet/replknet-XL_32xb64-coslr-300e_320_meg73mto1k.py
    Metadata:
      FLOPs: 128700000000
      Parameters: 335000000
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 87.57
        Top 5 Accuracy: 98.39
    Weights: https://download.openmmlab.com/mmclassification/v0/repvgg/repvgg-A0_3rdparty_4xb64-coslr-120e_in1k_20210909-883ab98c.pth
    Converted From:
      Weights: https://drive.google.com/u/0/uc?id=1tPC60El34GntXByIRHb-z-Apm4Y5LX1T&export=download
      Code: https://github.com/DingXiaoH/RepLKNet-pytorch/blob/main/replknet.py
  