Collections:
  - Name: EfficientNet
    Metadata:
      Training Data: ImageNet-1k
      Architecture:
        - 1x1 Convolution
        - Average Pooling
        - Convolution
        - Dense Connections
        - Dropout
        - Inverted Residual Block
        - RMSProp
        - Squeeze-and-Excitation Block
        - Swish
    Paper:
      URL: https://arxiv.org/abs/1905.11946v5
      Title: "EfficientNet: Rethinking Model Scaling for Convolutional Neural Networks"
    README: configs/efficientnet/README.md
    Code:
      Version: v0.20.1
      URL: https://github.com/open-mmlab/mmclassification/blob/v0.20.1/mmcls/models/backbones/efficientnet.py

Models:
  - Name: efficientnet-b0_3rdparty_8xb32_in1k
    Metadata:
      FLOPs: 16481180
      Parameters: 5288548
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 76.74
          Top 5 Accuracy: 93.17
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b0_3rdparty_8xb32_in1k_20220119-a7e2a0b1.pth
    Config: configs/efficientnet/efficientnet-b0_8xb32_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckpts/efficientnet-b0.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
  - Name: efficientnet-b0_3rdparty_8xb32-aa_in1k
    Metadata:
      FLOPs: 16481180
      Parameters: 5288548
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 77.26
          Top 5 Accuracy: 93.41
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b0_3rdparty_8xb32-aa_in1k_20220119-8d939117.pth
    Config: configs/efficientnet/efficientnet-b0_8xb32_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckptsaug/efficientnet-b0.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
  - Name: efficientnet-b0_3rdparty_8xb32-aa-advprop_in1k
    Metadata:
      FLOPs: 16481180
      Parameters: 5288548
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 77.53
          Top 5 Accuracy: 93.61
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b0_3rdparty_8xb32-aa-advprop_in1k_20220119-26434485.pth
    Config: configs/efficientnet/efficientnet-b0_8xb32-01norm_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/advprop/efficientnet-b0.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
  - Name: efficientnet-b1_3rdparty_8xb32_in1k
    Metadata:
      FLOPs: 27052224
      Parameters: 7794184
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 78.68
          Top 5 Accuracy: 94.28
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b1_3rdparty_8xb32_in1k_20220119-002556d9.pth
    Config: configs/efficientnet/efficientnet-b1_8xb32_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckpts/efficientnet-b1.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
  - Name: efficientnet-b1_3rdparty_8xb32-aa_in1k
    Metadata:
      FLOPs: 27052224
      Parameters: 7794184
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 79.20
          Top 5 Accuracy: 94.42
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b1_3rdparty_8xb32-aa_in1k_20220119-619d8ae3.pth
    Config: configs/efficientnet/efficientnet-b1_8xb32_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckptsaug/efficientnet-b1.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
  - Name: efficientnet-b1_3rdparty_8xb32-aa-advprop_in1k
    Metadata:
      FLOPs: 27052224
      Parameters: 7794184
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 79.52
          Top 5 Accuracy: 94.43
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b1_3rdparty_8xb32-aa-advprop_in1k_20220119-5715267d.pth
    Config: configs/efficientnet/efficientnet-b1_8xb32-01norm_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/advprop/efficientnet-b1.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
  - Name: efficientnet-b2_3rdparty_8xb32_in1k
    Metadata:
      FLOPs: 34346386
      Parameters: 9109994
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 79.64
          Top 5 Accuracy: 94.80
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b2_3rdparty_8xb32_in1k_20220119-ea374a30.pth
    Config: configs/efficientnet/efficientnet-b2_8xb32_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckpts/efficientnet-b2.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
  - Name: efficientnet-b2_3rdparty_8xb32-aa_in1k
    Metadata:
      FLOPs: 34346386
      Parameters: 9109994
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 80.21
          Top 5 Accuracy: 94.96
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b2_3rdparty_8xb32-aa_in1k_20220119-dd61e80b.pth
    Config: configs/efficientnet/efficientnet-b2_8xb32_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckptsaug/efficientnet-b2.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
  - Name: efficientnet-b2_3rdparty_8xb32-aa-advprop_in1k
    Metadata:
      FLOPs: 34346386
      Parameters: 9109994
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 80.45
          Top 5 Accuracy: 95.07
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b2_3rdparty_8xb32-aa-advprop_in1k_20220119-1655338a.pth
    Config: configs/efficientnet/efficientnet-b2_8xb32-01norm_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/advprop/efficientnet-b2.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
  - Name: efficientnet-b3_3rdparty_8xb32_in1k
    Metadata:
      FLOPs: 58641904
      Parameters: 12233232
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 81.01
          Top 5 Accuracy: 95.34
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b3_3rdparty_8xb32_in1k_20220119-4b4d7487.pth
    Config: configs/efficientnet/efficientnet-b3_8xb32_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckpts/efficientnet-b3.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
  - Name: efficientnet-b3_3rdparty_8xb32-aa_in1k
    Metadata:
      FLOPs: 58641904
      Parameters: 12233232
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 81.58
          Top 5 Accuracy: 95.67
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b3_3rdparty_8xb32-aa_in1k_20220119-5b4887a0.pth
    Config: configs/efficientnet/efficientnet-b3_8xb32_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckptsaug/efficientnet-b3.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
  - Name: efficientnet-b3_3rdparty_8xb32-aa-advprop_in1k
    Metadata:
      FLOPs: 58641904
      Parameters: 12233232
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 81.81
          Top 5 Accuracy: 95.69
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b3_3rdparty_8xb32-aa-advprop_in1k_20220119-53b41118.pth
    Config: configs/efficientnet/efficientnet-b3_8xb32-01norm_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/advprop/efficientnet-b3.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
  - Name: efficientnet-b4_3rdparty_8xb32_in1k
    Metadata:
      FLOPs: 121870624
      Parameters: 19341616
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 82.57
          Top 5 Accuracy: 96.09
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b4_3rdparty_8xb32_in1k_20220119-81fd4077.pth
    Config: configs/efficientnet/efficientnet-b4_8xb32_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckpts/efficientnet-b4.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
  - Name: efficientnet-b4_3rdparty_8xb32-aa_in1k
    Metadata:
      FLOPs: 121870624
      Parameters: 19341616
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 82.95
          Top 5 Accuracy: 96.26
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b4_3rdparty_8xb32-aa_in1k_20220119-45b8bd2b.pth
    Config: configs/efficientnet/efficientnet-b4_8xb32_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckptsaug/efficientnet-b4.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
  - Name: efficientnet-b4_3rdparty_8xb32-aa-advprop_in1k
    Metadata:
      FLOPs: 121870624
      Parameters: 19341616
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 83.25
          Top 5 Accuracy: 96.44
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b4_3rdparty_8xb32-aa-advprop_in1k_20220119-38c2238c.pth
    Config: configs/efficientnet/efficientnet-b4_8xb32-01norm_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/advprop/efficientnet-b4.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
  - Name: efficientnet-b5_3rdparty_8xb32_in1k
    Metadata:
      FLOPs: 243879440
      Parameters: 30389784
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 83.18
          Top 5 Accuracy: 96.47
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b5_3rdparty_8xb32_in1k_20220119-e9814430.pth
    Config: configs/efficientnet/efficientnet-b5_8xb32_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckpts/efficientnet-b5.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
  - Name: efficientnet-b5_3rdparty_8xb32-aa_in1k
    Metadata:
      FLOPs: 243879440
      Parameters: 30389784
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 83.82
          Top 5 Accuracy: 96.76
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b5_3rdparty_8xb32-aa_in1k_20220119-2cab8b78.pth
    Config: configs/efficientnet/efficientnet-b5_8xb32_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckptsaug/efficientnet-b5.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
  - Name: efficientnet-b5_3rdparty_8xb32-aa-advprop_in1k
    Metadata:
      FLOPs: 243879440
      Parameters: 30389784
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 84.21
          Top 5 Accuracy: 96.98
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b5_3rdparty_8xb32-aa-advprop_in1k_20220119-f57a895a.pth
    Config: configs/efficientnet/efficientnet-b5_8xb32-01norm_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/advprop/efficientnet-b5.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
  - Name: efficientnet-b6_3rdparty_8xb32-aa_in1k
    Metadata:
      FLOPs: 412002408
      Parameters: 43040704
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 84.05
          Top 5 Accuracy: 96.82
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b6_3rdparty_8xb32-aa_in1k_20220119-45b03310.pth
    Config: configs/efficientnet/efficientnet-b6_8xb32_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckptsaug/efficientnet-b6.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
  - Name: efficientnet-b6_3rdparty_8xb32-aa-advprop_in1k
    Metadata:
      FLOPs: 412002408
      Parameters: 43040704
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 84.74
          Top 5 Accuracy: 97.14
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b6_3rdparty_8xb32-aa-advprop_in1k_20220119-bfe3485e.pth
    Config: configs/efficientnet/efficientnet-b6_8xb32-01norm_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/advprop/efficientnet-b6.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
  - Name: efficientnet-b7_3rdparty_8xb32-aa_in1k
    Metadata:
      FLOPs: 715526512
      Parameters: 66347960
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 84.38
          Top 5 Accuracy: 96.88
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b7_3rdparty_8xb32-aa_in1k_20220119-bf03951c.pth
    Config: configs/efficientnet/efficientnet-b7_8xb32_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckptsaug/efficientnet-b7.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
  - Name: efficientnet-b7_3rdparty_8xb32-aa-advprop_in1k
    Metadata:
      FLOPs: 715526512
      Parameters: 66347960
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 85.14
          Top 5 Accuracy: 97.23
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b7_3rdparty_8xb32-aa-advprop_in1k_20220119-c6dbff10.pth
    Config: configs/efficientnet/efficientnet-b7_8xb32-01norm_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/advprop/efficientnet-b7.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
  - Name: efficientnet-b8_3rdparty_8xb32-aa-advprop_in1k
    Metadata:
      FLOPs: 1092755326
      Parameters: 87413142
    In Collections: EfficientNet
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 85.38
          Top 5 Accuracy: 97.28
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b8_3rdparty_8xb32-aa-advprop_in1k_20220119-297ce1b7.pth
    Config: configs/efficientnet/efficientnet-b8_8xb32-01norm_in1k.py
    Converted From:
      Weights: https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/advprop/efficientnet-b8.tar.gz
      Code: https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
