name: 🐞 Bug report
description: Create a report to help us improve
labels: ["bug"]
title: "[Bug] "
body:
  - type: markdown
    attributes:
      value: |
        If you have already identified the reason, we strongly appreciate you creating a new PR according to [the tutorial](https://mmpretrain.readthedocs.io/en/master/community/CONTRIBUTING.html)!
        If you need our help, please fill in the following form to help us to identify the bug.

  - type: dropdown
    id: version
    attributes:
      label: Branch
      description: Which branch/version are you using?
      options:
        - main branch (mmpretrain version)
        - mmcls-1.x branch (v1.0.0rc6 or other 1.x version)
        - mmcls-0.x branch (v0.25.0 or other 0.x version)
    validations:
      required: true

  - type: textarea
    id: describe
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: |
        Please provide a clear and concise description of what the bug is.
        Preferably a simple and minimal code snippet that we can reproduce the error by running the code.
      placeholder: |
        A clear and concise description of what the bug is.

        ```python
        # Sample code to reproduce the problem
        ```

        ```shell
        The command or script you run.
        ```

        ```
        The error message or logs you got, with the full traceback.
        ```

  - type: textarea
    id: environment
    validations:
      required: true
    attributes:
      label: Environment
      description: |
        Please run `python -c "import mmpretrain.utils;import pprint;pprint.pp(dict(mmpretrain.utils.collect_env()))"` to collect necessary environment information and paste it here.
      placeholder: |
        ```python
        # The output the above command
        ```

  - type: textarea
    id: other
    attributes:
      label: Other information
      description: |
        Tell us anything else you think we should know.

        1. Did you make any modifications on the code or config?
        2. What do you think might be the reason?
