name: 💬 寻求帮助
description: 其他类型的问题需要帮助
labels: ["help wanted"]

body:
  - type: markdown
    attributes:
      value: |
        推荐使用英语模板 General question，以便你的问题帮助更多人。

  - type: checkboxes
    id: prerequisite
    attributes:
      label: 我已试图查询该问题
      options:
        - label: 我已经查阅了相关 issue，没有找到相关帮助。
          required: true
        - label: 我已经查询了[官方文档](https://mmclassification.readthedocs.io/zh_CN/master/)，没有找到相关帮助。
          required: true

  - type: textarea
    id: describe
    validations:
      required: true
    attributes:
      label: 描述该问题
      placeholder: |
        1. 我阅读了文档，仍不清楚如何使用 xxx 功能。
        2. 其他问题
