Collections:
  - Name: SimMIM
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - AdamW
      Training Resources: 16x A100 GPUs
      Architecture:
        - Swin
    Paper:
        URL: https://arxiv.org/abs/2111.09886
        Title: "SimMIM: A Simple Framework for Masked Image Modeling"
    README: configs/simmim/README.md

Models:
  - Name: simmim_swin-base-w6_8xb256-amp-coslr-100e_in1k-192px
    In Collection: SimMIM
    Metadata:
      Epochs: 100
      Batch Size: 2048
    Results: null
    Config: configs/simmim/simmim_swin-base-w6_8xb256-amp-coslr-100e_in1k-192px.py
    Weights: https://download.openmmlab.com/mmselfsup/1.x/simmim/simmim_swin-base_8xb256-amp-coslr-100e_in1k-192/simmim_swin-base_8xb256-amp-coslr-100e_in1k-192_20220829-0e15782d.pth
    Downstream:
      - swin-base-w6_simmim-100e-pre_8xb256-coslr-100e_in1k-192px
      - swin-base-w7_simmim-100e-pre_8xb256-coslr-100e_in1k
  - Name: swin-base-w6_simmim-100e-pre_8xb256-coslr-100e_in1k-192px
    In Collection: SimMIM
    Metadata:
      Epochs: 100
      Batch Size: 2048
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 82.7
    Config: configs/simmim/benchmarks/swin-base-w6_8xb256-coslr-100e_in1k-192px.py
    Weights: https://download.openmmlab.com/mmselfsup/1.x/simmim/simmim_swin-base_8xb256-amp-coslr-100e_in1k-192/swin-base_ft-8xb256-coslr-100e_in1k/swin-base_ft-8xb256-coslr-100e_in1k_20220829-9cf23aa1.pth
  - Name: swin-base-w7_simmim-100e-pre_8xb256-coslr-100e_in1k
    In Collection: SimMIM
    Metadata:
      Epochs: 100
      Batch Size: 2048
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 83.5
    Config: configs/simmim/benchmarks/swin-base-w7_8xb256-coslr-100e_in1k.py

  - Name: simmim_swin-base-w6_16xb128-amp-coslr-800e_in1k-192px
    In Collection: SimMIM
    Metadata:
      Epochs: 100
      Batch Size: 2048
    Results: null
    Config: configs/simmim/simmim_swin-base-w6_16xb128-amp-coslr-800e_in1k-192px.py
    Weights: https://download.openmmlab.com/mmselfsup/1.x/simmim/simmim_swin-base_16xb128-amp-coslr-800e_in1k-192/simmim_swin-base_16xb128-amp-coslr-800e_in1k-192_20220916-a0e931ac.pth
    Downstream:
      - swin-base-w6_simmim-800e-pre_8xb256-coslr-100e_in1k-192px
  - Name: swin-base-w6_simmim-800e-pre_8xb256-coslr-100e_in1k-192px
    In Collection: SimMIM
    Metadata:
      Epochs: 100
      Batch Size: 2048
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 83.8
    Config: configs/simmim/benchmarks/swin-base-w6_8xb256-coslr-100e_in1k-192px.py
    Weights: https://download.openmmlab.com/mmselfsup/1.x/simmim/simmim_swin-base_8xb256-amp-coslr-100e_in1k-192/swin-base_ft-8xb256-coslr-100e_in1k/swin-base_ft-8xb256-coslr-100e_in1k_20220829-9cf23aa1.pth

  - Name: simmim_swin-large-w12_16xb128-amp-coslr-800e_in1k-192px
    In Collection: SimMIM
    Metadata:
      Epochs: 100
      Batch Size: 2048
    Results: null
    Config: configs/simmim/simmim_swin-large-w12_16xb128-amp-coslr-800e_in1k-192px.py
    Weights: https://download.openmmlab.com/mmselfsup/1.x/simmim/simmim_swin-large_16xb128-amp-coslr-800e_in1k-192/simmim_swin-large_16xb128-amp-coslr-800e_in1k-192_20220916-4ad216d3.pth
    Downstream:
      - swin-large-w14_simmim-800e-pre_8xb256-coslr-100e_in1k
  - Name: swin-large-w14_simmim-800e-pre_8xb256-coslr-100e_in1k
    In Collection: SimMIM
    Metadata:
      Epochs: 100
      Batch Size: 2048
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 84.8
    Config: configs/simmim/benchmarks/swin-large-w14_8xb256-coslr-100e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/1.x/simmim/simmim_swin-large_16xb128-amp-coslr-800e_in1k-192/swin-large_ft-8xb256-coslr-ws14-100e_in1k-224/swin-large_ft-8xb256-coslr-ws14-100e_in1k-224_20220916-d4865790.pth
