Collections:
  - Name: Inception V3
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Epochs: 100
      Batch Size: 256
      Architecture:
        - Inception
    Paper:
      URL: http://arxiv.org/abs/1512.00567
      Title: "Rethinking the Inception Architecture for Computer Vision"
    README: configs/inception_v3/README.md
    Code:
      URL: https://github.com/open-mmlab/mmpretrain/blob/v1.0.0rc1/configs/inception_v3/metafile.yml
      Version: v1.0.0rc1

Models:
  - Name: inception-v3_3rdparty_8xb32_in1k
    Metadata:
      FLOPs: 5745177632
      Parameters: 23834568
    In Collection: Inception V3
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 77.57
          Top 5 Accuracy: 93.58
    Weights: https://download.openmmlab.com/mmclassification/v0/inception-v3/inception-v3_3rdparty_8xb32_in1k_20220615-dcd4d910.pth
    Config: configs/inception_v3/inception-v3_8xb32_in1k.py
    Converted From:
      Weights: https://download.pytorch.org/models/inception_v3_google-0cc3c7bd.pth
      Code: https://github.com/pytorch/vision/blob/main/torchvision/models/inception.py#L28
