Collections:
  - Name: ArcFace
    Metadata:
      Training Data: InShop
      Architecture:
        - Additive Angular Margin Loss
    Paper:
      URL: https://arxiv.org/abs/1801.07698
      Title: 'ArcFace: Additive Angular Margin Loss for Deep Face Recognition'
    README: configs/arcface/README.md
    Code:
      Version: v1.0.0rc3
      URL: https://github.com/open-mmlab/mmpretrain/blob/v1.0.0rc3/mmcls/models/heads/margin_head.py

Models:
  - Name: resnet50-arcface_inshop
    Metadata:
      FLOPs: 16571226112
      Parameters: 31693888
    In Collection: ArcFace
    Results:
      - Dataset: InShop
        Metrics:
          Recall@1: 90.18
          mAP@10: 69.30
        Task: Image Retrieval
    Weights: https://download.openmmlab.com/mmclassification/v0/arcface/resnet50-arcface_inshop_20230202-b766fe7f.pth
    Config: configs/arcface/resnet50-arcface_8xb32_inshop.py
