Collections:
  - Name: EfficientFormer
    Metadata:
      Training Data: ImageNet-1k
      Architecture:
        - Pooling
        - 1x1 Convolution
        - LayerScale
        - MetaFormer
    Paper:
      URL: https://arxiv.org/pdf/2206.01191.pdf
      Title: "EfficientFormer: Vision Transformers at MobileNet Speed"
    README: configs/efficientformer/README.md
    Code:
      Version: v0.24.0
      URL: https://github.com/open-mmlab/mmclassification/blob/v0.24.0/mmcls/models/backbones/efficientformer.py

Models:
  - Name: efficientformer-l1_3rdparty_8xb128_in1k
    Metadata:
      FLOPs: 1304601088
      Parameters: 12278696
    In Collections: EfficientFormer
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 80.2
          Top 5 Accuracy: 93.51
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/poolformer/poolformer-s12_3rdparty_32xb128_in1k_20220414-f8d83051.pth
    Config: configs/efficientformer/efficientformer-l1_8xb128_in1k.py
    Converted From:
      Weights: https://drive.google.com/file/d/11SbX-3cfqTOc247xKYubrAjBiUmr818y/view?usp=sharing
      Code: https://github.com/snap-research/EfficientFormer
  - Name: efficientformer-l3_3rdparty_8xb128_in1k
    Metadata:
      Training Data: ImageNet-1k
      FLOPs: 3737045760
      Parameters: 27456152
    In Collections: EfficientFormer
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 80.33
          Top 5 Accuracy: 95.05
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/poolformer/poolformer-s24_3rdparty_32xb128_in1k_20220414-d7055904.pth
    Config: configs/efficientformer/efficientformer-l3_8xb128_in1k.py
    Converted From:
      Weights: https://drive.google.com/file/d/1OyyjKKxDyMj-BcfInp4GlDdwLu3hc30m/view?usp=sharing
      Code: https://github.com/snap-research/EfficientFormer
  - Name: efficientformer-l7_3rdparty_8xb128_in1k
    Metadata:
      FLOPs: 9492747264
      Parameters: 68436952
    In Collections: EfficientFormer
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 81.43
          Top 5 Accuracy: 95.45
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/poolformer/poolformer-s36_3rdparty_32xb128_in1k_20220414-d78ff3e8.pth
    Config: configs/efficientformer/efficientformer-l7_8xb128_in1k.py
    Converted From:
      Weights: https://drive.google.com/file/d/1cVw-pctJwgvGafeouynqWWCwgkcoFMM5/view?usp=sharing
      Code: https://github.com/snap-research/EfficientFormer