Collections:
  - Name: SparK
    Metadata:
      Architecture:
        - Dense Connections
        - GELU
        - Layer Normalization
        - Multi-Head Attention
        - Scaled Dot-Product Attention
    Paper:
      Title: 'Designing BERT for Convolutional Networks: Sparse and Hierarchical Masked Modeling'
      URL: https://arxiv.org/abs/2301.03580
    README: configs/spark/README.md
    Code:
      URL: null
      Version: null

Models:
  - Name: spark_sparse-resnet50_800e_in1k
    Metadata:
      FLOPs: 4100000000
      Parameters: 37971000
      Training Data:
        - ImageNet-1k
    In Collection: SparK
    Results: null
    Weights: https://download.openmmlab.com/mmpretrain/v1.0/spark/spark_sparse-resnet50_8xb512-amp-coslr-800e_in1k/spark_sparse-resnet50_8xb512-amp-coslr-800e_in1k_20230612-e403c28f.pth
    Config: configs/spark/spark_sparse-resnet50_8xb512-amp-coslr-800e_in1k.py
    Downstream:
      - resnet50_spark-pre_300e_in1k
  - Name: resnet50_spark-pre_300e_in1k
    Metadata:
      FLOPs: 1310000000
      Parameters: 23520000
      Training Data:
        - ImageNet-1k
    In Collection: SparK
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 80.1
          Top 5 Accuracy: 94.9
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmpretrain/v1.0/spark/spark_sparse-resnet50_8xb512-amp-coslr-800e_in1k/resnet50_8xb256-coslr-300e_in1k/resnet50_8xb256-coslr-300e_in1k_20230612-f86aab51.pth
    Config: configs/spark/benchmarks/resnet50_8xb256-coslr-300e_in1k.py

  - Name: spark_sparse-convnextv2-tiny_800e_in1k
    Metadata:
      FLOPs: 4470000000
      Parameters: 39732000
      Training Data:
        - ImageNet-1k
    In Collection: SparK
    Results: null
    Weights: https://download.openmmlab.com/mmpretrain/v1.0/spark/spark_sparse-convnextv2-tiny_16xb256-amp-coslr-800e_in1k/spark_sparse-convnextv2-tiny_16xb256-amp-coslr-800e_in1k_20230612-b0ea712e.pth
    Config: configs/spark/spark_sparse-convnextv2-tiny_16xb256-amp-coslr-800e_in1k.py
    Downstream:
      - convnextv2-tiny_spark-pre_300e_in1k
  - Name: convnextv2-tiny_spark-pre_300e_in1k
    Metadata:
      FLOPs: 4469631744
      Parameters: 28635496
      Training Data:
        - ImageNet-1k
    In Collection: SparK
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 82.8
          Top 5 Accuracy: 96.3
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmpretrain/v1.0/spark//spark_sparse-convnextv2-tiny_16xb256-amp-coslr-800e_in1k/convnextv2-tiny_8xb256-coslr-300e_in1k/convnextv2-tiny_8xb256-coslr-300e_in1k_20230612-ffc78743.pth
    Config: configs/spark/benchmarks/convnextv2-tiny_8xb256-coslr-300e_in1k.py
