Collections:
  - Name: PoolFormer
    Metadata:
      Training Data: ImageNet-1k
      Architecture:
        - Pooling
        - 1x1 Convolution
        - LayerScale
    Paper:
      URL: https://arxiv.org/abs/2111.11418
      Title: MetaFormer is Actually What You Need for Vision
    README: configs/poolformer/README.md
    Code:
      Version: v0.22.1
      URL: https://github.com/open-mmlab/mmclassification/blob/v0.22.1/mmcls/models/backbones/poolformer.py

Models:
  - Name: poolformer-s12_3rdparty_32xb128_in1k
    Metadata:
      FLOPs: 1871399424
      Parameters: 11915176
    In Collections: PoolFormer
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 77.24
          Top 5 Accuracy: 93.51
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/poolformer/poolformer-s12_3rdparty_32xb128_in1k_20220414-f8d83051.pth
    Config: configs/poolformer/poolformer-s12_32xb128_in1k.py
    Converted From:
      Weights: https://github.com/sail-sg/poolformer/releases/download/v1.0/poolformer_s12.pth.tar
      Code: https://github.com/sail-sg/poolformer
  - Name: poolformer-s24_3rdparty_32xb128_in1k
    Metadata:
      Training Data: ImageNet-1k
      FLOPs: 3510411008
      Parameters: 21388968
    In Collections: PoolFormer
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 80.33
          Top 5 Accuracy: 95.05
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/poolformer/poolformer-s24_3rdparty_32xb128_in1k_20220414-d7055904.pth
    Config: configs/poolformer/poolformer-s24_32xb128_in1k.py
    Converted From:
      Weights: https://github.com/sail-sg/poolformer/releases/download/v1.0/poolformer_s24.pth.tar
      Code: https://github.com/sail-sg/poolformer
  - Name: poolformer-s36_3rdparty_32xb128_in1k
    Metadata:
      FLOPs: 5149422592
      Parameters: 30862760
    In Collections: PoolFormer
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 81.43
          Top 5 Accuracy: 95.45
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/poolformer/poolformer-s36_3rdparty_32xb128_in1k_20220414-d78ff3e8.pth
    Config: configs/poolformer/poolformer-s36_32xb128_in1k.py
    Converted From:
      Weights: https://github.com/sail-sg/poolformer/releases/download/v1.0/poolformer_s36.pth.tar
      Code: https://github.com/sail-sg/poolformer
  - Name: poolformer-m36_3rdparty_32xb128_in1k
    Metadata:
      Training Data: ImageNet-1k
      FLOPs: 8960175744
      Parameters: 56172520
    In Collections: PoolFormer
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 82.14
          Top 5 Accuracy: 95.71
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/poolformer/poolformer-m36_3rdparty_32xb128_in1k_20220414-c55e0949.pth
    Config: configs/poolformer/poolformer-m36_32xb128_in1k.py
    Converted From:
      Weights: https://github.com/sail-sg/poolformer/releases/download/v1.0/poolformer_m36.pth.tar
      Code: https://github.com/sail-sg/poolformer
  - Name: poolformer-m48_3rdparty_32xb128_in1k
    Metadata:
      FLOPs: 11801805696
      Parameters: 73473448
    In Collections: PoolFormer
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 82.51
          Top 5 Accuracy: 95.95
        Task: Image Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/poolformer/poolformer-m48_3rdparty_32xb128_in1k_20220414-9378f3eb.pth
    Config: configs/poolformer/poolformer-m48_32xb128_in1k.py
    Converted From:
      Weights: https://github.com/sail-sg/poolformer/releases/download/v1.0/poolformer_m48.pth.tar
      Code: https://github.com/sail-sg/poolformer
