Collections:
  - Name: ResNeXt
    Metadata:
      Training Data: ImageNet
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Epochs: 100
      Batch Size: 256
      Architecture:
        - ResNeXt
    Paper: https://openaccess.thecvf.com/content_cvpr_2017/html/Xie_Aggregated_Residual_Transformations_CVPR_2017_paper.html
    README: configs/resnext/README.md

Models:
- Config: configs/resnext/resnext50_32x4d_b32x8_imagenet.py
  In Collection: ResNeXt
  Metadata:
    FLOPs: 4270000000
    Parameters: 25030000
  Name: resnext50_32x4d_b32x8_imagenet
  Results:
  - Dataset: ImageNet
    Metrics:
      Top 1 Accuracy: 77.92
      Top 5 Accuracy: 93.74
    Task: Image Classification
  Weights: https://download.openmmlab.com/mmclassification/v0/resnext/resnext50_32x4d_batch256_imagenet_20200708-c07adbb7.pth
- Config: configs/resnext/resnext101_32x4d_b32x8_imagenet.py
  In Collection: ResNeXt
  Metadata:
    FLOPs: 8030000000
    Parameters: 44180000
  Name: resnext101_32x4d_b32x8_imagenet
  Results:
  - Dataset: ImageNet
    Metrics:
      Top 1 Accuracy: 78.7
      Top 5 Accuracy: 94.34
    Task: Image Classification
  Weights: https://download.openmmlab.com/mmclassification/v0/resnext/resnext101_32x4d_batch256_imagenet_20200708-87f2d1c9.pth
- Config: configs/resnext/resnext101_32x8d_b32x8_imagenet.py
  In Collection: ResNeXt
  Metadata:
    FLOPs: 16500000000
    Parameters: 88790000
  Name: resnext101_32x8d_b32x8_imagenet
  Results:
  - Dataset: ImageNet
    Metrics:
      Top 1 Accuracy: 79.22
      Top 5 Accuracy: 94.52
    Task: Image Classification
  Weights: https://download.openmmlab.com/mmclassification/v0/resnext/resnext101_32x8d_batch256_imagenet_20200708-1ec34aa7.pth
- Config: configs/resnext/resnext152_32x4d_b32x8_imagenet.py
  In Collection: ResNeXt
  Metadata:
    FLOPs: 11800000000
    Parameters: 59950000
  Name: resnext152_32x4d_b32x8_imagenet
  Results:
  - Dataset: ImageNet
    Metrics:
      Top 1 Accuracy: 79.06
      Top 5 Accuracy: 94.47
    Task: Image Classification
  Weights: https://download.openmmlab.com/mmclassification/v0/resnext/resnext152_32x4d_batch256_imagenet_20200708-aab5034c.pth
