Collections:
  - Name: CSRA
    Metadata:
      Training Data: PASCAL VOC 2007
      Architecture:
        - Class-specific Residual Attention
    Paper:
      URL: https://arxiv.org/abs/2108.02456
      Title: 'Residual Attention: A Simple but Effective Method for Multi-Label Recognition'
    README: configs/csra/README.md
    Code:
      Version: v0.24.0
      URL: https://github.com/open-mmlab/mmpretrain/blob/v0.24.0/mmcls/models/heads/multi_label_csra_head.py

Models:
  - Name: resnet101-csra_1xb16_voc07-448px
    Metadata:
      FLOPs: 4120000000
      Parameters: 23550000
    In Collection: CSRA
    Results:
      - Dataset: PASCAL VOC 2007
        Metrics:
          mAP: 94.98
          OF1: 90.80
          CF1: 89.16
        Task: Multi-Label Classification
    Weights: https://download.openmmlab.com/mmclassification/v0/csra/resnet101-csra_1xb16_voc07-448px_20220722-29efb40a.pth
    Config: configs/csra/resnet101-csra_1xb16_voc07-448px.py
