Collections:
  - Name: ResNet
    Metadata:
      Training Data: ImageNet
      Training Resources: 8x V100 GPUs
      Epochs: 100
      Batch Size: 256
      Architecture:
        - ResNet
    Paper: https://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html
    README: configs/fp16/README.md

Models:
- Config: configs/fp16/resnet50_b32x8_fp16_dynamic_imagenet.py
  In Collection: ResNet
  Metadata:
    FLOPs: 4.12 G
    Parameters: 25.56 M
    Training Techniques:
        - SGD with Momentum
        - Weight Decay
        - Mixed Precision Training
  Name: ResNet-50
  Results:
  - Dataset: ImageNet
    Metrics:
      Top 1 Accuracy: 76.32
      Top 5 Accuracy: 93.04
    Task: Image Classification
  Weights: https://download.openmmlab.com/mmclassification/v0/fp16/resnet50_batch256_fp16_imagenet_20210320-b3964210.pth
