Collections:
  - Name: EVA
    Metadata:
      Architecture:
        - Attention Dropout
        - Convolution
        - Dense Connections
        - Dropout
        - GELU
        - Layer Normalization
        - Multi-Head Attention
        - Scaled Dot-Product Attention
        - Tanh Activation
    Paper:
      URL: https://arxiv.org/abs/2211.07636
      Title: 'EVA: Exploring the Limits of Masked Visual Representation Learning at Scale'
    README: configs/eva/README.md
    Code:
      URL:
      Version:

Models:
  - Name: eva-g-p14_3rdparty_30m
    In Collection: EVA
    Metadata:
      FLOPs: 267174833024
      Parameters: 1011596672
      Training Data:
        - merged-30M
    Results: null
    Weights: https://download.openmmlab.com/mmclassification/v0/eva/eva-g-p14_3rdparty_30m_20221213-3b7aca97.pth
    Converted From:
      Weights: https://huggingface.co/BAAI/EVA/blob/main/eva_psz14.pt
      Code: https://github.com/baaivision/EVA
    Config: configs/eva/eva-g-p14_headless.py

  - Name: eva-g-p16_3rdparty_30m
    In Collection: EVA
    Metadata:
      FLOPs: 203517463424
      Parameters: 1011315072
      Training Data:
        - merged-30M
    Results: null
    Weights: https://download.openmmlab.com/mmclassification/v0/eva/eva-g-p16_3rdparty_30m_20221213-7bed23ee.pth
    Converted From:
      Weights: https://huggingface.co/BAAI/EVA/blob/main/eva_psz14to16.pt
      Code: https://github.com/baaivision/EVA
    Config: configs/eva/eva-g-p16_headless.py

  - Name: eva-g-p14_30m-pre_3rdparty_in21k
    In Collection: EVA
    Metadata:
      FLOPs: 267174833024
      Parameters: 1011596672
      Training Data:
        - merged-30M
        - ImageNet-21k
    Results: null
    Weights: https://download.openmmlab.com/mmclassification/v0/eva/eva-g-p14_30m-pre_3rdparty_in21k_20221213-d72285b7.pth
    Converted From:
      Weights: https://huggingface.co/BAAI/EVA/blob/main/eva_21k_224px_psz14.pt
      Code: https://github.com/baaivision/EVA
    Config: configs/eva/eva-g-p14_headless.py

  - Name: eva-g-p14_30m-in21k-pre_3rdparty_in1k-336px
    In Collection: EVA
    Metadata:
      FLOPs: 620642757504
      Parameters: 1013005672
      Training Data:
        - merged-30M
        - ImageNet-21k
        - ImageNet-1k
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 89.61
        Top 5 Accuracy: 98.93
    Weights: https://download.openmmlab.com/mmclassification/v0/eva/eva-g-p14_30m-in21k-pre_3rdparty_in1k-336px_20221213-210f9071.pth
    Converted From:
      Weights: https://huggingface.co/BAAI/EVA/blob/main/eva_21k_1k_336px_psz14_ema_89p6.pt
      Code: https://github.com/baaivision/EVA
    Config: configs/eva/eva-g-p14_8xb16_in1k-336px.py

  - Name: eva-g-p14_30m-in21k-pre_3rdparty_in1k-560px
    In Collection: EVA
    Metadata:
      FLOPs: 1906761591680
      Parameters: 1014447464
      Training Data:
        - merged-30M
        - ImageNet-21k
        - ImageNet-1k
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 89.71
        Top 5 Accuracy: 98.96
    Weights: https://download.openmmlab.com/mmclassification/v0/eva/eva-g-p14_30m-in21k-pre_3rdparty_in1k-560px_20221213-fa1c3652.pth
    Converted From:
      Weights: https://huggingface.co/BAAI/EVA/blob/main/eva_21k_1k_560px_psz14_ema_89p7.pt
      Code: https://github.com/baaivision/EVA
    Config: configs/eva/eva-g-p14_8xb16_in1k-560px.py

  - Name: eva-l-p14_3rdparty-mim_in21k
    In Collection: EVA
    Metadata:
      FLOPs: 81075147776
      Parameters: 303178752
      Training Data:
        - ImageNet-21k
    Results: null
    Weights: https://download.openmmlab.com/mmclassification/v0/eva/eva-l-p14_3rdparty-mim_in21k_20221213-3a5da50b.pth
    Converted From:
      Weights: https://huggingface.co/BAAI/EVA/blob/main/eva_l_psz14.pt
      Code: https://github.com/baaivision/EVA
    Config: configs/eva/eva-l-p14_headless.py

  - Name: eva-l-p14_mim-pre_3rdparty_in21k
    In Collection: EVA
    Metadata:
      FLOPs: 81075147776
      Parameters: 303178752
      Training Data:
        - ImageNet-21k
    Results: null
    Weights: https://download.openmmlab.com/mmclassification/v0/eva/eva-l-p14_mim-pre_3rdparty_in21k_20221213-8f194fa2.pth
    Converted From:
      Weights: https://huggingface.co/BAAI/EVA/blob/main/eva_l_psz14_21k_ft.pt
      Code: https://github.com/baaivision/EVA
    Config: configs/eva/eva-l-p14_headless.py

  - Name: eva-l-p14_mim-pre_3rdparty_in1k-336px
    In Collection: EVA
    Metadata:
      FLOPs: 191100916736
      Parameters: 304531432
      Training Data:
        - ImageNet-21k
        - ImageNet-1k
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 88.66
        Top 5 Accuracy: 98.75
    Weights: https://download.openmmlab.com/mmclassification/v0/eva/eva-l-p14_mim-pre_3rdparty_in1k-336px_20221214-07785cfd.pth
    Converted From:
      Weights: https://huggingface.co/BAAI/EVA/blob/main/eva_l_psz14_336px_1k_ft_88p65.pt
      Code: https://github.com/baaivision/EVA
    Config: configs/eva/eva-l-p14_8xb16_in1k-336px.py

  - Name: eva-l-p14_mim-in21k-pre_3rdparty_in1k-336px
    In Collection: EVA
    Metadata:
      FLOPs: 191100916736
      Parameters: 304531432
      Training Data:
        - ImageNet-21k
        - ImageNet-1k
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 89.17
        Top 5 Accuracy: 98.86
    Weights: https://download.openmmlab.com/mmclassification/v0/eva/eva-l-p14_mim-in21k-pre_3rdparty_in1k-336px_20221213-f25b7634.pth
    Converted From:
      Weights: https://huggingface.co/BAAI/EVA/blob/main/eva_l_psz14_336px_21k_to_1k_ft_89p2.pt
      Code: https://github.com/baaivision/EVA
    Config: configs/eva/eva-l-p14_8xb16_in1k-336px.py

  - Name: eva-l-p14_mim-pre_3rdparty_in1k-196px
    In Collection: EVA
    Metadata:
      FLOPs: 61565981696
      Parameters: 304142312
      Training Data:
        - ImageNet-21k
        - ImageNet-1k
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 87.94
        Top 5 Accuracy: 98.50
    Weights: https://download.openmmlab.com/mmclassification/v0/eva/eva-l-p14_mim-pre_3rdparty_in1k-196px_20221214-2adf4d28.pth
    Converted From:
      Weights: https://huggingface.co/BAAI/EVA/blob/main/eva_l_psz14_196px_1k_ft_88p0.pt
      Code: https://github.com/baaivision/EVA
    Config: configs/eva/eva-l-p14_8xb16_in1k-196px.py

  - Name: eva-l-p14_mim-in21k-pre_3rdparty_in1k-196px
    In Collection: EVA
    Metadata:
      FLOPs: 61565981696
      Parameters: 304142312
      Training Data:
        - ImageNet-21k
        - ImageNet-1k
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 88.58
        Top 5 Accuracy: 98.65
    Weights: https://download.openmmlab.com/mmclassification/v0/eva/eva-l-p14_mim-in21k-pre_3rdparty_in1k-196px_20221213-b730c7e7.pth
    Converted From:
      Weights: https://huggingface.co/BAAI/EVA/blob/main/eva_l_psz14_196px_21k_to_1k_ft_88p6.pt
      Code: https://github.com/baaivision/EVA
    Config: configs/eva/eva-l-p14_8xb16_in1k-196px.py
